
x=[-4:.1:4];
f=sin(3.*cos(x)).*cos(3.*sin(x));
max(f);
find(f==max(f));
%SE SI VUOLE TROVARE IL MASSIMO DI UNA FUNZIONE IN UN DATO INTERVALLO DICHIARO IL VETTORE DELLE X DOVE CALCOLO LA FUNZIONE, SUCCESSIVAMENTE
%USO LA FUNZIONE FIND DOVE METTO DA UN LATO IL VETTORE E DALL'ALTRO IL VALORE, QUESTA FUNZIONE MI RESTITUISCE LA POSIZIONE.